### ISSUE TITLE
Fiji Umbrella issue

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1379]
- [x] Misc Improvements https://github.com/AlphaWallet/alpha-wallet-android/issues/1290

- [x] Update ER20 + Ether Default Token View [Fiji] https://github.com/AlphaWallet/alpha-wallet-android/issues/1237

- [x] Update token icons in Wallet tab [Fiji] https://github.com/AlphaWallet/alpha-wallet-android/issues/1086

- [x] Provide a Clear Browser Cache function in the setting page https://github.com/AlphaWallet/alpha-wallet-android/issues/722

- [ ] Activity: GitHub Issue not yet created

**Comment by AW-STJ** [comment]
@JamesSmartCell created for tracking the Fiji progress. Let me know if there is any other work that I might have missed out.

**Comment by JamesSmartCell** [comment]
#722 can be closed.
