### ISSUE TITLE
Checklist for 30th October 

### ISSUE THREAD

**Issue by AW-STJ** [AlphaWallet/alpha-wallet-android#1650]
Can we list out our key focuses for this fortnight?

**Comment by JamesSmartCell** [comment]
- [ ] All cosmetic fix PRs from AndroidX upgrade merged.
- [ ] Token receive functionality for ERC20 and ERC721
- [ ] Full generic ERC20 activity support.

**Comment by AW-STJ** [comment]
All issues tested and works in the 3.12.0(132)
