### ISSUE TITLE
Construct blank activities, update graphic assets and create widgets [Samoa]

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#1831]
This issue is creating the graphic skeletons for the big Samoa update. I have tried to add in how to get the data, but the first priority is getting the skeletons of each view to appear; once they do we can then try to add the correct data.

Please create a 'Samoa Update' WIP PR branch to being with, and then have sub-PR's going into that main branch.

Some changes can take immediate effect (eg the new graphics in the TokenHolder for the ticker data) as the data is already sourced and is ready in the Realm database.

- [ ] #1767 Create Portfolio, Performance and Stats pages. Not sure if these should be full Activity or just full screen Dialog boxes? Or widgets? Use whichever pattern you think is most applicable I'll follow it.

- [ ] #1768 Update Wallet Tab page. This one is quite big, but we can source most of the data for it as is. First update the graphic assets for each ```TokenHolder``` graphic with as appropriate. This shouldn't require any new data - you can see how to access the ticker data for each item from the existing ```TokenHolder``` class. 

Add the ability to group tokens by 'Savings', 'NFT' and implement the text headers for those. Identifying NFT is easy but identifying 'Savings' vs normal tokens is not so trivial, we can just filter for 'compound' keyword maybe?

Add the token search bar as shown. Filter by name is slightly tricky you'll have to cross reference a realm wildcard search (like in the ```TokenManagementActivty``` class) with the received ```TokenCardMeta``` list in ```TokensService```.

- [ ] #1769 Can you build this with the layout but make some fake data for now, for the total value. For wallet value, use ETH for now but we'll add in all the ERC20 with value later. See how it's accessed from the Blockie, where you can select a new wallet or look at 'all wallets'. That All Wallets page should be a separate page (not re-using the walletfragment!) The reason for this is that there'll be enough differences that it'll make the code messy. Of course we re-use a lot of other elements like the ```TokensAdapter```.

- [ ] #1771 This is creating the layout used in #1770 below. This page is called ```ERC20DetailActivity``` and is accessed from clicking on (eg) the Ethereum token - create a viewpager with the 'Info', Activity and Alerts tabs, which sits in the current ```ERC20DetailActivity```

- [ ] #1770 History chart. Have a look at this page: https://app.zeplin.io/project/5d088205bff2d15de6a4397b/screen/5e787d4564f2a76eb147065f. After clicking on the (?) icon in the top right you should be at this page: https://zpl.io/VKx0yA6 

We are still working on the history chart data, but I believe @hboon now has a working solution. For now, just add a fake graphic from the zeplin; I can work on getting it working after it's in. In the case of the compound DAI information seen in the above screen this information probably comes from TokenScript, so probably don't try adding it yet - I will confirm this at a later date.

- [ ] #1772  Price Alerts: Build a new fragment and add layouts and holders as seen. Can you also add the input (maybe re-use InputAmount widget). Once this is done we'll add a background service to provide these alerts.

Feel free to add comments on all of the issue screens concerning flow etc; we'll try to answer those as soon as possible.

**Comment by JamesSmartCell** [comment]
Hi @justindg. Please refer to the interactive prototype for flow:

https://invis.io/7TZHRQ8W265

In particular, how to move from the wallet summary to sub-wallets, and also see that the send/receive + extra (bottom sheet) is still at the bottom of the page that you get to (currently called ```class ERC20DetailActivity```) when you click on each token.
