### ISSUE TITLE
Issues with native swap

### ISSUE THREAD

**Issue by JamesSmartCell** [AlphaWallet/alpha-wallet-android#2692]
- [x] Reset amount when changing the token (reproduce: use send max on a token, then change the token to one with zero balance). via #2732
- [x] Prioritise source drop-down tokens same as WalletFragment; ie use Fiat value from high to low, then alphabetical order for the dropdown on source tokens. via #2724
- [x] Refresh swap price every 30 (?) seconds same as Uniswap does (check Uniswap maybe and time their refresh rate).
- [x] Add chain token to destination tokens, so we can swap to Eth (or Polygon etc).  via #2732
- [x] Expand swap provider message to include toolDetails.name provider from Quote. See //TODO: Expand swap provider. via #2732
- [x] Add the chain symbol after the 'fees', and also add fiat price similar to the gas widget. See //TODO: Needs to say 'Eth' via #2732
