### ISSUE TITLE
Remove mutually exclusive mode for mainnet and testnet so mainnet chains are always available, but testnets are off by default until users flip the switch and acknowledge

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/alpha-wallet-android#3023]
A. Remove the switch for mainnet
B. Keep the switch for testnet — unchanged
C. Keep the prompt for acknowledgment when enabling testnets
D. List of mainnets should always be available in the list of chains
E. The header in Wallet tab for the current testnet-mode should be removed
F. We always show the header with fiat value for mainnets that are enabled (if any, otherwise $0), in Wallet tab

<img width="687" alt="Screenshot 2022-12-30 at 3 23 46 PM" src="https://user-images.githubusercontent.com/56189/210045111-e43583d1-14aa-4daa-8c39-86cfd02e6fd9.png">
<img width="840" alt="Screenshot 2022-12-30 at 3 23 50 PM" src="https://user-images.githubusercontent.com/56189/210045124-9443ca30-5cc2-4cc7-9417-c14e7a7c1e03.png">

**Comment by seabornlee** [comment]
I'll take this high priority issue because Justin is on leave.

**Comment by seabornlee** [comment]
** Tasks:**

- [ ] Remove the switch for mainnet
- [ ] Remove testnet header
- [ ] Show testnet under mainnet when it's enabled
- [ ] Show the header with fiat value for enabled mainnets

**Comment by JamesSmartCell** [comment]
I like this improvement a lot :) Switching the testnet chains on and off is a chore.

**Comment by seabornlee** [comment]
@JamesSmartCell Do you know why user can choose network when add token, I found after choose a network, it still scan all networks.

**Comment by JamesSmartCell** [comment]
> @JamesSmartCell Do you know why user can choose network when add token, I found after choose a network, it still scan all networks.

Yes - you can set a 'priority' network for faster scanning. It's kind of a hangover from when the wallet could only show one chain at a time. We should probably remove it as TBH most ppl would rather just scan and wait, rather than setting up a specific  network to start first. If you remove this you can also slightly simplify the scanning.

So - best to remove that icon and ability to set networks, since now, yes it scans all networks and asks you to switch on the networks for tokens you want to add but which aren't active.

**Comment by seabornlee** [comment]
> > @JamesSmartCell Do you know why user can choose network when add token, I found after choose a network, it still scan all networks.
> 
> Yes - you can set a 'priority' network for faster scanning. It's kind of a hangover from when the wallet could only show one chain at a time. We should probably remove it as TBH most ppl would rather just scan and wait, rather than setting up a specific network to start first. If you remove this you can also slightly simplify the scanning.
> 
> So - best to remove that icon and ability to set networks, since now, yes it scans all networks and asks you to switch on the networks for tokens you want to add but which aren't active.

Clear. Thanks for elaborating. I'd like to remove it.
